### ISSUE TITLE
Using 'X-FORWARDED-FOR' as rate limit expression

### ISSUE THREAD

**Issue by ricristian** [MarcGiffing/bucket4j-spring-boot-starter#176]
I'll try to reopen this topic because in servlet it is not going to work. 
Any advice ? 

org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method getHeaders() cannot be found on type org.apache.catalina.connector.RequestFacade

https://github.com/MarcGiffing/bucket4j-spring-boot-starter/issues/97

this is my ml configuration

```
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-bucketss
      url: /api/v1/authenticate
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 3
              time: 1
              unit:
                minutes
    - cache-name: rate-limit-bucketss
      url: /api/v1/.*
      strategy: all
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: getHeaders()['X-Forwarded-For']
          bandwidths:
            - capacity: 5
              time: 1
              unit: minutes
    ```
