### ISSUE TITLE
Add a Default Http Response configuration

### ISSUE THREAD

**Issue by alex-sira** [MarcGiffing/bucket4j-spring-boot-starter#402]
Is this project still manteined?
Is it possible to add a default for the Response?
Something like
```
bucket4j:
  enabled: true
  default-http-response-body: '{"error": "Too Many Requests. Rate limit exceeded. Please try again later."}'
  default-http-status: 429
  filters:
    - .......
```
