### ISSUE TITLE
Configuration for multiple rate limits on the same Servlet Filter

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/bucket4j-spring-boot-starter#5]
1. Not logged in  - IP Based
2. Testuser - Based on username with specific bandwidth
2. Normal user - Based on username with other bandwidth

**Comment by MarcGiffing** [comment]
Maybe something like this:
```
bucket4j:
  rate-limit:
    enabled: true
    configs:
    - cache-name: buckets   
      filter-method: servlet 
      url: /*
      rate-limits:
        -
        filter-key-type: expression
        skip-condition: (!@securityService.signedIn())
        expression: getRemoteAddr()
        bandwidths:
        - 
          capacity: 1
          time: 1
          unit: seconds
      -
        filter-key-type: expression
        skip-condition: (!@securityService.getGroup() == 'testuser')
        expression: @securityService.username()
        bandwidths:
        - 
          capacity: 1
          time: 10
          unit: seconds
      -
        filter-key-type: expression
        skip-condition: @securityService.getGroup() == 'testuser'
        expression: @securityService.username()
        bandwidths:
        - 
          capacity: 50
          time: 10
          unit: seconds
```
