### ISSUE TITLE
SecurityContextHolder with AbstractPreAuthenticatedProcessingFilter

### ISSUE THREAD

**Issue by cod-r** [MarcGiffing/bucket4j-spring-boot-starter#60]
Hi,

I'm trying to rate limit my API using an API key from the URL
I have my API secured by an API key using this method:
```
@Configuration
@EnableWebSecurity
public class APISecurityConfig extends WebSecurityConfigurerAdapter {

    @Value("${principal.hashed.key}")
    private String principalHashedKey;

    @Override
    protected void configure(HttpSecurity httpSecurity) throws Exception {
        APIKeyAuthFilter filter = new APIKeyAuthFilter();

        filter.setAuthenticationManager(authentication -> {
            String urlApiKey = (String) authentication.getPrincipal();
            if (!BCrypt.checkpw(urlApiKey, principalHashedKey)) {
                throw new BadCredentialsException("The API key was not found or not the expected value.");
            }
            authentication.setAuthenticated(true);
            return authentication;
        });

        httpSecurity
                .csrf()
                .disable()
                .authorizeRequests()
                .antMatchers("/v3/api-docs/**", "/swagger-ui/**", "/swagger-ui.html", "/documentation.html")
                .permitAll()
                .anyRequest()
                .authenticated()
                .and()
                .addFilter(filter)
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
    }

}
```
and the filter:
```
public class APIKeyAuthFilter extends AbstractPreAuthenticatedProcessingFilter {

    @Override
    protected Object getPreAuthenticatedPrincipal(HttpServletRequest request) {
        return request.getParameter("api_key");
    }

    @Override
    protected Object getPreAuthenticatedCredentials(HttpServletRequest request) {
        return "N/A";
    }

}
```
What is happening is I'm getting the api_key from the url and then check it against the hashed api_key. If they match then the request passes. Everithing works well.

My problem is that when using this:
`bucket4j.filters[0].rate-limits[0].execute-condition=@securityService.isAuthorized()
`
```
@Service
public class SecurityService {

    public boolean isAuthorized() {
        return SecurityContextHolder.getContext().getAuthentication() != null &&
                SecurityContextHolder.getContext().getAuthentication().isAuthenticated();
    }

}
```
the SecurityContextHolder.getContext().getAuthentication() is always null
but if I try to use it in my controller it is not null anymore. I guess it has something to do with the fact that I'm using a filter and not the classic approach with username and pass.
Is there something I can do to get the status of auth?

**Comment by majoer** [comment]
Getting the same problem with SecurityContextHolder.getContext().getAuthentication() always being null. Running Spring Boot Starter 2.2.5.RELEASE

I was debugging my auto-configuration of OAuth2 resource-server and noticed the SPEL expression is executed before the token is fully verified. Could this be related?

application.yml
``` yaml
bucket4j:
  enabled: true
  filters:
    - cache-name: requests
      url: .*
      rate-limits:
        - expression: "@authorizationService.subClaim()"
          bandwidths:
            - capacity: 5
              time: 10
              unit: seconds
spring: 
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ...
```

```java

@Configuration
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Value("${feature-toggle.auth:true}")
    private boolean auth_enabled;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        if (auth_enabled) {
            http
                    .authorizeRequests()
                    .mvcMatchers(OPTIONS, "/**").permitAll()
                    .mvcMatchers(GET, "/actuator/ready").permitAll()
                    .mvcMatchers(GET, "/actuator/health").permitAll()
                    .mvcMatchers(GET, "/actuator/prometheus").permitAll()
                    .anyRequest().authenticated()
                    .and()
                    .oauth2ResourceServer().jwt();
        } else {
            http.authorizeRequests().anyRequest().permitAll();
        }
    }
}

```
```java
@Service
public class AuthorizationService {

    public String subClaim() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        return authentication.getName(); // <-- NullPointerException
    }
}

```

**Comment by majoer** [comment]
Took me a day to figure it out. [This post]( https://stackoverflow.com/questions/26126586/spring-security-access-the-current-authenticated-user-inside-a-servlet-filter) made me realize that Spring security context is only accessible after some security filter has been applied first. Depending on how many filters you have, filter-order must be high enough, so that Spring security context is available when the Bucket4J filter is applied.

```yaml
bucket4j:
  enabled: true
  filters:
    - cache-name: requests
      filter-order: 1000 # <-- This must be greater that whatever filter initializes Spring Security Context
      url: .*
      rate-limits:
        - expression: "@authorizationService.subClaim()"
          bandwidths:
            - capacity: 5
              time: 10
              unit: seconds
```
