### ISSUE TITLE
rate-limits not working for application.properties

### ISSUE THREAD

**Issue by sysmat** [MarcGiffing/bucket4j-spring-boot-starter#72]
It's very strange if I use **application.yml** it works fine, but when I use **application.properties** it doesn't work!

* spring-boot-starter-parent:2.3.4.RELEASE
* com.giffing.bucket4j.spring.boot.starter:0.2.0
* application.properties(not working) using https://github.com/MarcGiffing/bucket4j-spring-boot-starter#bucket4j-properties
```properties
spring.cache.type=caffeine
spring.cache.cache-names=rate-limit-buckets            
spring.cache.caffeine.spec=maximumSize=100000,expireAfterAccess=3600s

# enable/disable bucket4j support
bucket4j.enabled=true 
bucket4j.filters[0].cache-name=rate-limit-buckets
bucket4j.filters[0].filter-method=servlet
bucket4j.filters[0].url=/report/add
bucket4j.filters[0].strategy=first
bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=1
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=1
bucket4j.filters[0].rate-limits[0].bandwidths[0].unit=minutes
bucket4j.filters[0].rate-limits[0].bandwidths[0].fixed-refill-interval=1
bucket4j.filters[0].rate-limits[0].bandwidths[0].fixed-refill-interval-unit=minutes
```
* application.yml(working)
```yml
spring:
    cache:
        cache-names:
            - rate-limit-buckets
        caffeine:
            spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
  - cache-name: rate-limit-buckets
    url: /report/add
    strategy: first
    rate-limits:
    - bandwidths:
      - capacity: 1
        time: 1
        unit: minutes
        fixed-refill-interval: 1
        fixed-refill-interval-unit: minutes
```
* pom.xml
```xml
<dependency>
            <groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
            <artifactId>bucket4j-spring-boot-starter</artifactId>
            <version>0.2.0</version>            
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <!-- This cache must be thogether -->
        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>            
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>jcache</artifactId>            
        </dependency>
```
I'm missing something or doing something wrong?

Regards
