### ISSUE TITLE
Rate limiting is not applied when using multiple custom cache

### ISSUE THREAD

**Issue by fistons** [MarcGiffing/bucket4j-spring-boot-starter#73]
In our application, we use several cache with separate custom configuration:

```java
    @Bean
    public CaffeineCache cacheOneCaffeineCache() {
        return new CaffeineCache("cacheOne",
                  Caffeine.newBuilder()
                        .maximumSize(512)
                        .expireAfterWrite(Duration.ofHours(1))
                        .build());
    }

    @Bean
    public CaffeineCache cacheTwoCaffeineCache() {
        return new CaffeineCache("cacheTwo",
                 Caffeine.newBuilder()
                        .maximumSize(1)
                        .expireAfterWrite(Duration.ofDays(1))
                        .build());
    }

    @Bean
    public CaffeineCache rateLimitingCaffeineCache() {
        return new CaffeineCache("rateLimiting",
                 Caffeine.newBuilder()
                        .maximumSize(1000000)
                        .expireAfterWrite(Duration.ofHours(1))
                        .build());
    }
```

with our application.yml looking like this:
```yaml
bucket4j:
  enabled: true
  filters:
    - cache-name: rateLimiting
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 1
              time: 1
              unit: minutes
              fixed-refill-interval: 1
              fixed-refill-interval-unit: minutes
```

Sadly, the rate limiting is not applied. The only way I could make it work is by configuring my cache in the application.yml, not with beans, but this way I cannot use different configuration for each cache:
```yaml
spring:
  cache:
    cache-names:
      - cacheOne
      - cacheTwo
      - rateLimiting
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
    - cache-name: rateLimiting
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 1
              time: 1
              unit: minutes
              fixed-refill-interval: 1
              fixed-refill-interval-unit: minutes
```

Is there a way to be able to use bucket4j with caches configured with beans?
