### ISSUE TITLE
Request for documentation of fixed-refill-interval and fixed-refill-interval-unit properties.

### ISSUE THREAD

**Issue by RaduFurnea** [MarcGiffing/bucket4j-spring-boot-starter#75]
Hello all. This request comes off an issue I ran into while running a basic example of limiting.

build.gradle: 
```  
  implementation 'com.giffing.bucket4j.spring.boot.starter:bucket4j-spring-boot-starter:0.2.0'
  implementation 'org.springframework.boot:spring-boot-starter-cache'
  implementation 'javax.cache:cache-api'
  implementation 'com.github.ben-manes.caffeine:caffeine:2.8.2'
  implementation 'com.github.ben-manes.caffeine:jcache:2.8.2'
```

My test case is a limit of 2 requests per minute for a single endpoint. The configuration I was hoping to work is this: 

```
bucket4j:
  enabled: true
  filters:
  - cache-name: rate-limit-buckets
    url: /hello
    strategy: first
    http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
    rate-limits:
    - bandwidths:
      - capacity: 2
        time: 1
        unit: minutes
```

I make 2 requests, the 3rd is blocked. After 30 seconds, another request goes trough. At about 1 minute after the initial request another request works, but the second doesn't, which is the worng behaviour.

By adding ```fixed-refill-interval: 1``` and ```fixed-refill-interval-unit: minutes``` the situation was fixed, as requests from 3 to n were blocked in the first minute, and the same in the second minute and so on.

I failed to find a concrete explanation of these attributes and I was wondering if I can find such documentation. 

Many thanks!
