### ISSUE TITLE
Why is ServletRequestFilter not loaded?

### ISSUE THREAD

**Issue by xianzheTM** [MarcGiffing/bucket4j-spring-boot-starter#82]
```
spring:
  cache:
    cache-names:
      - buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      filter-method: servlet
      filter-order: 1
      http-response-body: { "message": "Too many requests" }
      url: /cs/login.*
      rate-limits:
        - expression: getRemoteAddr()
          bandwidths:
            - capacity: 1
              time: 2
              unit: seconds
```
This is my application.yml.
I found that ServletRequestFilter does not exist.
![image](https://user-images.githubusercontent.com/25103583/122770481-10b50600-d2d8-11eb-9a0c-4715a379d81e.png)
Is this not imported?
