### ISSUE TITLE
Enabling the same metrics for many filters

### ISSUE THREAD

**Issue by scottbass47** [MarcGiffing/bucket4j-spring-boot-starter#96]
This may already be possible but I couldn't find any information in the documentation. Say you have the following metrics defined for one of your filters:
```yaml
metrics:
      tags:
        - key: IP
          expression: getRemoteAddr()
          types: REJECTED_COUNTER # for data privacy reasons the IP should only be collected on bucket rejections
        - key: USERNAME
          expression: "@securityService.username() != null ? @securityService.username() : 'anonym'"
        - key: URL
          expression: request.getRequestURI()
```
Now, when creating another filter you also want to collect metrics. Since prometheus requires the same tags to be defined for every metric, this configuration must be duplicated for all other filters. Is there anyway either through the yaml config or through programmatic configuration to be able to declare the metrics in one spot for all filters? Thank you.
